-- SnapUp Events security hardening migration.
-- Run on staging first, after taking a schema/ACL backup. This migration assumes
-- the application tables listed in the audit exist in public.
begin;

alter table public.users add column if not exists token_version integer not null default 0;
alter table public.event_guests add column if not exists guest_access_token_hash text;
alter table public.media add column if not exists bytes bigint not null default 0;
alter table public.media add column if not exists cloudinary_public_id text;
alter table public.media add column if not exists resource_type text;
alter table public.media add column if not exists delivery_type text not null default 'authenticated';
alter table public.media add column if not exists format text;

alter table public.users drop constraint if exists users_token_version_check;
alter table public.users add constraint users_token_version_check check (token_version >= 0);
alter table public.event_guests drop constraint if exists event_guests_name_length_check;
alter table public.event_guests add constraint event_guests_name_length_check
  check (char_length(btrim(guest_name)) between 1 and 80);
alter table public.media drop constraint if exists media_bytes_check;
alter table public.media add constraint media_bytes_check check (bytes >= 0 and bytes <= 52428800);
alter table public.media drop constraint if exists media_message_length_check;
alter table public.media add constraint media_message_length_check
  check (message is null or char_length(message) between 1 and 2000);
alter table public.event_settings drop constraint if exists event_settings_upload_limit_check;
alter table public.event_settings add constraint event_settings_upload_limit_check
  check (max_upload_per_guest between 1 and 200);
alter table public.event_settings drop constraint if exists event_settings_storage_limit_check;
alter table public.event_settings add constraint event_settings_storage_limit_check
  check (max_storage_per_guest between 1 and 2048);

create unique index if not exists media_likes_media_key_unique
  on public.media_likes (media_id, like_key);
create unique index if not exists event_guests_event_normalized_name_unique
  on public.event_guests (event_id, lower(btrim(guest_name)));
create unique index if not exists event_event_code_unique on public.event (event_code);

create table if not exists public.cloudinary_cleanup_outbox (
  cleanup_id bigint generated by default as identity primary key,
  public_id text not null,
  resource_type text not null default 'image',
  delivery_type text not null default 'authenticated',
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  attempts integer not null default 0
);

-- Serialize quota checks per guest. The row lock closes concurrent upload races.
create or replace function public.enforce_guest_media_quota()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_max_count integer;
  v_max_bytes bigint;
  v_count bigint;
  v_bytes bigint;
begin
  perform 1 from public.event_guests g
   where g.guest_id = new.guest_id and g.event_id = new.event_id
   for update;
  if not found then raise exception 'guest does not belong to event' using errcode = '42501'; end if;

  select least(coalesce(s.max_upload_per_guest, 20), 200),
         least(coalesce(s.max_storage_per_guest, 250), 2048)::bigint * 1024 * 1024
    into v_max_count, v_max_bytes
    from public.event_settings s where s.event_id = new.event_id;
  v_max_count := coalesce(v_max_count, 20);
  v_max_bytes := coalesce(v_max_bytes, 250::bigint * 1024 * 1024);

  select count(*), coalesce(sum(m.bytes), 0) into v_count, v_bytes
    from public.media m where m.event_id = new.event_id and m.guest_id = new.guest_id;
  if v_count + 1 > v_max_count then raise exception 'guest upload count exceeded' using errcode = 'P0001'; end if;
  if v_bytes + coalesce(new.bytes, 0) > v_max_bytes then raise exception 'guest storage quota exceeded' using errcode = 'P0001'; end if;
  return new;
end;
$$;

-- Deletes all account-owned relational data in one transaction. Cloudinary work
-- is placed in an outbox because an external API cannot join a DB transaction.
create or replace function public.delete_user_account(p_user_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_events bigint; v_media bigint;
begin
  perform 1 from public.users u where u.user_id::text = p_user_id for update;
  if not found then return jsonb_build_object('deleted', false); end if;

  insert into public.cloudinary_cleanup_outbox(public_id, resource_type, delivery_type)
  select distinct m.cloudinary_public_id, coalesce(m.resource_type, 'image'), coalesce(m.delivery_type, 'authenticated')
    from public.media m
   where m.cloudinary_public_id is not null and (
     m.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id)
     or m.guest_id in (select g.guest_id from public.event_guests g where g.user_id::text = p_user_id)
   );
  get diagnostics v_media = row_count;

  delete from public.media_likes l where l.media_id in (
    select m.media_id from public.media m where
      m.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id)
      or m.guest_id in (select g.guest_id from public.event_guests g where g.user_id::text = p_user_id));
  delete from public.media m where
    m.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id)
    or m.guest_id in (select g.guest_id from public.event_guests g where g.user_id::text = p_user_id);
  delete from public.event_invitations i where i.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id);
  delete from public.event_settings s where s.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id);
  delete from public.event_guests g where g.event_id in (select e.event_id from public.event e where e.user_id::text = p_user_id) or g.user_id::text = p_user_id;
  delete from public.event e where e.user_id::text = p_user_id;
  get diagnostics v_events = row_count;
  delete from public.password_reset_tokens r where r.user_id::text = p_user_id;
  delete from public.email_verification_tokens v where v.user_id::text = p_user_id;
  delete from public.users u where u.user_id::text = p_user_id;
  return jsonb_build_object('deleted', true, 'events', v_events, 'assets_queued', v_media);
end;
$$;
drop trigger if exists media_guest_quota_guard on public.media;
create trigger media_guest_quota_guard before insert on public.media
for each row execute function public.enforce_guest_media_quota();

-- Atomically claim a reset token, change the password and invalidate sessions.
create or replace function public.consume_password_reset(p_token_hash text, p_password_hash text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_user_id public.users.user_id%type;
begin
  update public.password_reset_tokens
     set used_at = now()
   where token_hash = p_token_hash and used_at is null and revoked_at is null and expires_at > now()
   returning user_id into v_user_id;
  if v_user_id is null then return false; end if;
  update public.users set password_hash = p_password_hash, token_version = token_version + 1
   where user_id = v_user_id and is_user_active = true;
  if not found then raise exception 'active user not found'; end if;
  update public.password_reset_tokens set revoked_at = now()
   where user_id = v_user_id and used_at is null and revoked_at is null;
  return true;
end;
$$;

-- Deny direct Data API access. Express remains the only public data boundary.
do $$
declare t text;
begin
  foreach t in array array[
    'users','password_reset_tokens','email_verification_tokens','event','event_settings',
    'event_guests','media','media_likes','packet_level','media_type','event_invitations','cloudinary_cleanup_outbox'
  ] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('revoke all on table public.%I from anon, authenticated', t);
      execute format('grant select, insert, update, delete on table public.%I to service_role', t);
    end if;
  end loop;
  foreach t in array array['events_media','pending_media'] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter view public.%I set (security_invoker = true)', t);
      execute format('revoke all on table public.%I from anon, authenticated', t);
      execute format('grant select on table public.%I to service_role', t);
    end if;
  end loop;
end $$;

revoke all on function public.consume_password_reset(text, text) from public, anon, authenticated;
grant execute on function public.consume_password_reset(text, text) to service_role;
revoke all on function public.delete_user_account(text) from public, anon, authenticated;
grant execute on function public.delete_user_account(text) to service_role;
revoke all on function public.enforce_guest_media_quota() from public, anon, authenticated;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

-- Storage is not used by this app. Ensure no public bucket remains accidentally exposed.
update storage.buckets set public = false where public = true;
revoke all on table storage.objects from anon, authenticated;
revoke all on table storage.buckets from anon, authenticated;

commit;
